/**
This file is automatically generated.  Do not modify
*/
package org.kairosdb.datastore.h2.orm;

import org.agileclick.genorm.runtime.GenOrmException;
import org.agileclick.genorm.runtime.GenOrmQueryRecord;
import org.agileclick.genorm.runtime.GenOrmQueryResultSet;
import org.agileclick.genorm.runtime.SQLQuery;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.xml.sax.Attributes;
import org.xml.sax.ContentHandler;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
*/
public class TagValuesByTagNameQuery extends TagValuesQuery
	{
	private static final Logger s_logger = LoggerFactory.getLogger(TagValuesByTagNameQuery.class.getName());

	public static final String QUERY_NAME = "tag_values_by_tag_name";
	public static final String QUERY = "select distinct \"value\" from tag where \"name\"= ?";
	private static final int ATTRIBUTE_COUNT = 1;
	private static Map<String, Integer> s_attributeIndex;
	private static String[] s_attributeNames = {
			"value",
			"tag"};

	static
		{
		s_attributeIndex = new HashMap<>();
		for (int I = 0; I < ATTRIBUTE_COUNT; I++)
			s_attributeIndex.put(s_attributeNames[I], I);
		}

		private final String m_tagName;

		private boolean m_serializable;



	//---------------------------------------------------------------------------
	public TagValuesByTagNameQuery(String tagName)
		{
		super();
		m_tagName = tagName;
		}

	//---------------------------------------------------------------------------
	public String getQueryName() { return (QUERY_NAME); }

	//---------------------------------------------------------------------------
	public String getQuery() { return (QUERY); }

	//---------------------------------------------------------------------------
	public void setSerializable(boolean serializable)
		{
		m_serializable = serializable;
		}

	//---------------------------------------------------------------------------
	public String toString()
		{
			StringBuilder sb = new StringBuilder();
			sb.append(this.getClass().getName());
			sb.append(" tagName=").append(String.valueOf(m_tagName));

			return (sb.toString());
		}

	//---------------------------------------------------------------------------
	public ResultSet runQuery()
		{
		java.sql.PreparedStatement genorm_statement = null;
		try
			{
			String genorm_query = QUERY;

			genorm_statement = GenOrmDataSource.prepareStatement(genorm_query);
			genorm_statement.setString(1, m_tagName);

			long genorm_queryTimeStart = 0L;
			if (s_logger.isInfoEnabled())
				{
				genorm_queryTimeStart = System.currentTimeMillis();
				}
				
			java.sql.ResultSet genorm_resultSet = genorm_statement.executeQuery();
			
			if (genorm_queryTimeStart != 0L)
				{
				long genorm_quryTime = System.currentTimeMillis() - genorm_queryTimeStart;
				s_logger.info(String.valueOf(genorm_quryTime));
				}
			
			return new SQLResultSet(genorm_resultSet, genorm_statement, genorm_query);
			}
		catch (java.sql.SQLException sqle)
			{
			try
				{
				if (genorm_statement != null)
					genorm_statement.close();
				}
			catch (java.sql.SQLException sqle2) { }
				
			throw new GenOrmException(sqle);
			}
		}
		
	//===========================================================================
	//Plugin Classes and Methods
		

	//===========================================================================
	private class SQLResultSet 
			implements ResultSet
		{
		private java.sql.ResultSet m_resultSet;
		private java.sql.Statement m_statement;
		private String m_query;
		private boolean m_onFirstResult;
		
		//------------------------------------------------------------------------
		//need to pass in the statement so it can be closed after the result set
		protected SQLResultSet(java.sql.ResultSet resultSet, java.sql.Statement statement, 
				String query)
			{
			m_resultSet = resultSet;
			m_statement = statement;
			m_query = query;
			m_onFirstResult = false;
			}
		
		//------------------------------------------------------------------------
		/**
			Closes any underlying java.sql.Result set and java.sql.Statement 
			that was used to create this results set.
		*/
		public void close()
			{
			try
				{
				m_resultSet.close();
				m_statement.close();
				}
			catch (java.sql.SQLException sqle)
				{
				throw new GenOrmException(sqle);
				}
			}
			
		//------------------------------------------------------------------------
		/**
			Returns the reults as an ArrayList of Record objects.
			The Result set is closed within this call
		*/
		public List<TagValuesData> getArrayList(int maxRows)
			{
			ArrayList<TagValuesData> results = new ArrayList<>();
			int count = 0;
			
			try
				{
				if (m_onFirstResult)
					{
					count ++;
					results.add(new TagValuesData(TagValuesByTagNameQuery.this, m_resultSet));
					}
					
				while (m_resultSet.next() && (count < maxRows))
					{
					count ++;
					results.add(new TagValuesData(TagValuesByTagNameQuery.this, m_resultSet));
					}
					
				if (m_resultSet.next())
					throw new GenOrmException("Bound of "+maxRows+" is too small for query ["+m_query+"]");
				}
			catch (java.sql.SQLException sqle)
				{
				throw new GenOrmException(sqle);
				}
				
			close();
			return (results);
			}
			
		//------------------------------------------------------------------------
		/**
			Returns the reults as an ArrayList of Record objects.
			The Result set is closed within this call
		*/
		public List<TagValuesData> getArrayList()
			{
			ArrayList<TagValuesData> results = new ArrayList<>();
			
			try
				{
				if (m_onFirstResult)
					results.add(new TagValuesData(TagValuesByTagNameQuery.this, m_resultSet));
					
				while (m_resultSet.next())
					results.add(new TagValuesData(TagValuesByTagNameQuery.this, m_resultSet));
				}
			catch (java.sql.SQLException sqle)
				{
				throw new GenOrmException(sqle);
				}
				
			close();
			return (results);
			}
			
		//------------------------------------------------------------------------
		/**
			Returns the underlying java.sql.ResultSet object
		*/
		public java.sql.ResultSet getResultSet()
			{
			return (m_resultSet);
			}
			
		//------------------------------------------------------------------------
		/**
			Returns the current record in the result set
		*/
		public TagValuesData getRecord()
			{
			TagValuesData ret;
			try
				{
				ret = new TagValuesData(TagValuesByTagNameQuery.this, m_resultSet);
				}
			catch (java.sql.SQLException sqle)
				{
				throw new GenOrmException(sqle);
				}
				
			return (ret);
			}
			
		//------------------------------------------------------------------------
		/**
			This call expects only one record in the result set.  If multiple records
			are found an excpetion is thrown.
			The ResultSet object is automatically closed by this call.
		*/
		public TagValuesData getOnlyRecord()
			{
			TagValuesData ret = null;
			
			try
				{
				if (m_resultSet.next())
					ret = new TagValuesData(TagValuesByTagNameQuery.this, m_resultSet);
					
				if (m_resultSet.next())
					throw new GenOrmException("Multiple rows returned in call from TagValuesQuery.ResultSet.getOnlyRecord");
				}
			catch (java.sql.SQLException sqle)
				{
				throw new GenOrmException(sqle);
				}
				
			close();
			return (ret);
			}
			
		//------------------------------------------------------------------------
		/**
			Returns true if there is another record in the result set.
		*/
		public boolean next()
			{
			boolean ret;
			m_onFirstResult = true;
			try
				{
				ret = m_resultSet.next();
				}
			catch (java.sql.SQLException sqle)
				{
				throw new GenOrmException(sqle);
				}
			
			return (ret);
			}
		}
		
	//===========================================================================
	}